name: Integration Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  use-tests-base:
    uses: ./.github/workflows/tests-base.yml
    with:
      test_type: integration
