name: Tests Base

on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run image
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.5.1

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Install dependencies
        run: poetry install

      - name: Run Unit Tests
        if: ${{ inputs.test_type == 'unit' }}
        run: |
          poetry run pytest tests/unit --verbose

      - name: Run Integration Tests
        if: ${{ inputs.test_type == 'integration' }}
        run: |
          poetry run pytest tests/integration --verbose
