name: Unit Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  use-tests-base:
    uses: ./.github/workflows/tests-base.yml
    with:
      test_type: unit
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
