name: Unit Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.5.1

      - name: Install dependencies
        run: poetry install

      - name: Run Unit Tests
        run: |
          poetry run pytest tests/unit --cov ./tomodo --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yuviherziger/tomodo
